name: Deploy React App To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: luckydoki-user

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Create .env file (필요한 경우)
        run: |
          echo "${{ secrets.REACT_ENV_FILE }}" > .env

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true # 이전에 실행중인 스크립트 중지
          script: |
            cd /home/ubuntu/${{ env.REPOSITORY_NAME }}
            sudo chown -R ubuntu:ubuntu .  # 현재 디렉토리 전체의 소유권을 ubuntu 사용자로 변경
            git pull origin main
            npm i --force
            sudo rm -rf build
            npm run build
            pm2 delete user || true  # user라는 이름의 프로세스가 없어도 에러 없이 진행
            pm2 serve build 3000 --name user
